/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    LoginPopup: typeof import('./../../src/components/LoginPopup/index.vue')['default']
    Skeleton: typeof import('./../../src/components/Skeleton/index.vue')['default']
    WdUpload: typeof import('wot-design-uni/components/wd-upload/wd-upload.vue')['default']
  }
}
